server:
  port: 8080
  reactive:
    session:
      cookie:
        same-site: lax
        http-only: true
        secure: true

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID:ekko-bff}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email

        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_PUBLIC_URL}/realms/${KEYCLOAK_REALM:ekko}/protocol/openid-connect/auth
            token-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM:ekko}/protocol/openid-connect/token
            user-info-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM:ekko}/protocol/openid-connect/userinfo
            jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM:ekko}/protocol/openid-connect/certs
            user-name-attribute: preferred_username

      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_PUBLIC_URL}/realms/${KEYCLOAK_REALM:ekko}
          jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM:ekko}/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webflux:

          httpclient:
            connect-timeout: 5000
            response-timeout: 10s

          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins:
                  - ${FRONTEND_URL:http://localhost:4200}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

          routes:

            - id: keycloak-userinfo-test
              uri: http://localhost:8180
              predicates:
                - Path=/test/relay
              filters:
                - SetPath=/realms/ekko/protocol/openid-connect/userinfo

            # --- Rutas de docs

            - id: identity-service-docs
              uri: lb://identity-service
              predicates:
                - Path=/api/identity/v3/api-docs/**
              filters:
                - StripPrefix=2

            - id: seller-service-docs
              uri: lb://seller-service
              predicates:
                - Path=/api/sellers/v3/api-docs/**
              filters:
                - StripPrefix=2

            - id: product-service-docs
              uri: lb://product-service
              predicates:
                - Path=/api/products/v3/api-docs/**
              filters:
                - StripPrefix=2

            - id: order-service-docs
              uri: lb://order-service
              predicates:
                - Path=/api/orders/v3/api-docs/**
              filters:
                - StripPrefix=2

            - id: payment-service-docs
              uri: lb://payment-service
              predicates:
                - Path=/api/payments/v3/api-docs/**
              filters:
                - StripPrefix=2

            - id: review-service-docs
              uri: lb://review-service
              predicates:
                - Path=/api/reviews/v3/api-docs/**
              filters:
                - StripPrefix=2

            - id: notification-service-docs
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/v3/api-docs/**
              filters:
                - StripPrefix=2



            # --- Rutas de negocio

            - id: seller-service
              uri: lb://seller-service
              predicates:
                - Path=/api/sellers/**,/api/admin/sellers/**
              filters:
                - TokenRelay
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@userOrIpKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: seller-cb
                    fallbackUri: forward:/fallback/sellers
                - StripPrefix=1

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**,/api/seller/products/**,/api/admin/products/**,/api/admin/categories/**,/api/admin/brands/**,/api/catalog/products/**,/api/categories/**,/api/brands/**,/api/seller/variants/**,/api/internal/**
              filters:
                - TokenRelay
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@userOrIpKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: product-cb
                    fallbackUri: forward:/fallback/products
                - StripPrefix=1

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders,/api/orders/**,/api/admin/orders,/api/admin/orders/**
              filters:
                - TokenRelay
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@userOrIpKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: order-cb
                    fallbackUri: forward:/fallback/orders
                - StripPrefix=1

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payments/**,/api/admin/payments/**,/api/vendor-accounts/**
              filters:
                - TokenRelay
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@userOrIpKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: payment-cb
                    fallbackUri: forward:/fallback/payments
                - StripPrefix=1

            - id: stripe-webhook
              uri: lb://payment-service
              predicates:
                - Path=/webhooks/stripe

            - id: review-service
              uri: lb://review-service
              predicates:
                - Path=/api/reviews/**,/api/admin/reviews/**,/api/product-reviews/**
              filters:
                - TokenRelay
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@userOrIpKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: review-cb
                - StripPrefix=1

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/**,/api/admin/notification-templates/**
              filters:
                - TokenRelay
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@userOrIpKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: notification-cb
                - StripPrefix=1
                
            - id: identity-service
              uri: lb://identity-service
              predicates:
                - Path=/api/identity/**
              filters:
                - TokenRelay
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@userOrIpKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: identity-cb
                    fallbackUri: forward:/fallback/identity
                - StripPrefix=1


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: identity-service
        url: /api/identity/v3/api-docs
      - name: seller-service
        url: /api/sellers/v3/api-docs
      - name: product-service
        url: /api/products/v3/api-docs
      - name: order-service
        url: /api/orders/v3/api-docs
      - name: payment-service
        url: /api/payments/v3/api-docs
      - name: review-service
        url: /api/reviews/v3/api-docs
      - name: notification-service
        url: /api/notifications/v3/api-docs

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

    instances:
      seller-cb:
        base-config: default
      product-cb:
        base-config: default
      order-cb:
        base-config: default
      payment-cb:
        base-config: default
      review-cb:
        base-config: default
      notification-cb:
        base-config: default

  timelimiter:
    configs:
      default:
        timeout-duration: 10s

    instances:
      seller-cb:
        base-config: default
      product-cb:
        base-config: default
      order-cb:
        base-config: default
      payment-cb:
        base-config: default
      review-cb:
        base-config: default
      notification-cb:
        base-config: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.web.server.csrf: TRACE
